# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'Colours'
pod 'FrameAccessor'
pod 'MBProgressHUD'
pod 'AFNetworking',  :inhibit_warnings => true
pod 'MagicalRecord', :inhibit_warnings => true